### ISSUE TITLE
Example .md file?

### ISSUE THREAD

**Issue by JoshOrndorff** [bmschmidt/MarkdownLectures#2]
This looks amazing and I'd love to use it.

Could you provide an example of one of your lectures in .md format (Like the System Builders one in your blog)?

**Comment by bmschmidt** [comment]
Sure--I've actually changed the input format recently, now that pandoc supports labelled div elements, so it will look a little different. I'll update to the most recent version first, and then try to bundle an example.

**Comment by bmschmidt** [comment]
Added a demo file along with pushing the pandoc 2.2 updates--the thing is greatly reduced from a full lecture, but shows a few things including autoplay of embedded youtube clips and the new div syntax.
